### ISSUE TITLE
Implementation of Deep Multi-Agent RL

### ISSUE THREAD

**Issue by IpadLi** [ssokota/mmd#1]
Hi,

Could you share the implementation for the deep marl experiments in the paper, i.e., Figure 3? I did not find where the DQN is used. Please correct me if I missed it.

Thanks.

**Comment by ssokota** [comment]
Hi,

The DQN code is here: https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/rl_response.py

The one change I made was to train DQN for 10 million time steps instead of 1 million episodes. Other than that, just set `game` and `exploitee` as desired and run the code as is (with `learner` set to `dqn`).

**Comment by IpadLi** [comment]
@ssokota Thanks for your quick response. I go through the codebase you released and another one by @ryan-dorazio, and also the open_spiel codebase. If I understand correctly, the current version only contains the tabular cases. I actually want to know more about the deep marl version as mentioned in the paper "We implemented MMD as a modification of RLlib’s (Liang et al., 2018) PPO implementation by changing the adaptive forward KL regularization to a reverse KL regularization." If you could share that part (provide the link if I missed it somewhere), it would be great and helpful because, in my understanding, the details of the **training** and **evaluation** might be quite different when the policy is represented by a neural network (in tabular cases, the policy somewhat can be called direct policy parameterization).

**Comment by ssokota** [comment]
The code referenced in the quotation is here:
https://github.com/ray-project/ray/blob/ray-1.12.0/rllib/agents/ppo/ppo_torch_policy.py

The changes mentioned in the quotation were to switch the direction of the KL on this line:
https://github.com/ray-project/ray/blob/ray-1.12.0/rllib/agents/ppo/ppo_torch_policy.py#L128
and to comment out the adaptivity here:
https://github.com/ray-project/ray/blob/ray-1.12.0/rllib/agents/ppo/ppo_torch_policy.py#L198-L201

**Comment by IpadLi** [comment]
@ssokota That's great! Although it's a simple modification, I would still like to suggest you release a complete version of the code because, for people who want to fully reproduce the results in the paper, it is much better to directly run the code you released, rather than first re-implement themselves and then run the re-implementation, which may cause different results. The differences may come from the different code structures, integration of ray and open_spiel, and training and evaluation pipelines.

**Comment by ssokota** [comment]
The setup for training is here:
https://github.com/ray-project/ray/blob/ray-1.12.0/rllib/examples/self_play_with_open_spiel.py

For the integration between RLlib and OpenSpiel, just modify the OpenSpiel wrapper to use information state tensors instead of observation tensors:
https://github.com/ray-project/ray/blob/ray-1.12.0/rllib/env/wrappers/open_spiel.py
